services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '${VITE_PORT:-8080}:80'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
